# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import search.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('osm_keys', models.TextField(blank=True, null=True, validators=[search.models.osm_keys_validator])),
                ('processing_rules', models.TextField(blank=True, null=True, validators=[search.models.preset_pr_validator])),
            ],
        ),
    ]
